# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://blog.example42.com
title: Example42 Blog
email: info@example42.com
author: Example42 PuppetMasters
description: > # "Example42 delivers Puppet training, consulting and development services. It provides consulting on automation and DevOps practices"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
plugins:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
include: ['guide/slides/beginner/file/_images/logoguide.jpg','guide/slides/beginner/file/_images/logoguide.jpg']

social:
  - title: github
    url: https://github.com/example42
  - title: linkedin
    url: https://www.linkedin.com/company/example42
  - title: xing
    url: https://www.xing.com/companies/example42
