# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.example42.com
title: Example42
email: info@example42.com
author: Example42 PuppetMasters 
description: > # "Example42 delivers Puppet training, consulting and development services. It provides consulting on automation and DevOps practices"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
include:
  - guide/slides/beginner/file/_images
  - guide/slides/beginner/file/_fonts

social:
  - title: github
    url: https://github.com/example42
  - title: linkedin
    url: https://www.linkedin.com/company/example42
  - title: xing
    url: https://www.xing.com/companies/example42
